#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    #apple_dist = []
    #orange_dist=[]
    sum_apple=0
    sum_orange=0
    for i in range(len(apples)):
        apple_dist = apples[i]+ a
        if apple_dist >=s and apple_dist <=t:
            sum_apple+=1 

    for j in range(len(oranges)):
        orange_dist = oranges[j]+b

        if orange_dist >=s and orange_dist <=t:
            sum_orange+=1
    print (sum_apple)
    print(sum_orange)




    


if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
